### PR TITLE
fix: missing await in `_dispatchUpdate`

### LINKED ISSUE #299: TypeError due to undefined `peer.userId`
I get `TypeError: Cannot read properties of undefined (reading 'toString')` in `telegram\Utils.js:1040` (`return peer.userId.toString();`) when trying to handle new messages I sent myself.

This is the code I use to handle new messages:

```ts
client.addEventHandler(async (event) => {
  console.log('got new message!');
}, new NewMessage({}));
```

`got new message!` is never printed, because the error above is thrown before that can happen.

### PR DESCRIPTION
**Pull request by robin-hartmann**
Fixes #299.

### CODE REVIEW

File: gramjs/client/updates.ts [hunk 1]
```diff
@@ -128,7 +128,7 @@ export async function _dispatchUpdate(
         let event = args.update;
         if (event) {
             if (!client._selfInputPeer) {
-                client.getMe(true).catch(() => {
+                await client.getMe(true).catch(() => {
```
Comment (robin-hartmann) [inline gramjs/client/updates.ts:131]: Without this `await`, `builder.build()` in line 139 of `updates.ts` is called before `client._selfInputPeer` has been set, so `undefined` is passed as `selfId`. This then causes a `new Api.PeerUser` to be constructed in line 150 of `NewMessage.ts` with its `userId` set to `undefined`.

Comment (painor) [reply gramjs/client/updates.ts:131]: this was kinda done on purpose because of QR logins a while ago. Can you switch this to a try catch instead of await .catch()  ?

I'll test it a bit and if everything is fine I'll merge

Comment (robin-hartmann) [reply gramjs/client/updates.ts]: Replaced the `.catch()` with `try/catch`.

**Comment by painor** [comment]
seems to be working fine
